import React, { useEffect, createElement } from 'react';

import { tMatch, transformMatchingElements } from '@/_helpers/dom-manipulators';
import { TabContentProps } from '@/_typings/agent-my-listings';
import { getAutoGeneratedPropertyInfo } from '@/_utilities/api-calls/call-prompt';
import { searchByPartOfClass } from '@/_utilities/rx-element-extractor';
import useFormEvent, { Events, PrivateListingData, ImagePreview } from '@/hooks/useFormEvent';

import Input from '@/_replacers/FilterFields/Input';
import SearchAddressCombobox from '@/_replacers/FilterFields/SearchAddressCombobox';
import RxDragNDrop from '@/components/RxDragNDrop';
import RxDropzone from '@/components/RxDropzone';
import useDebounce from '@/hooks/useDebounce';

export default function TabAi({ template, nextStepClick }: TabContentProps) {
  const tabEventState = useFormEvent<PrivateListingData>(Events.PrivateListingForm);
  const debouncedPropmt = useDebounce(tabEventState?.data?.prompt ?? '', 600);

  useEffect(() => {
    if (debouncedPropmt.length > 5) {
      getAutoGeneratedPropertyInfo(debouncedPropmt).then(res => {
        tabEventState.fireEvent({ generatedPrompt: res });
      });
    }
    return () => {};
  }, [debouncedPropmt, tabEventState]);

  const blockNext = () => ![tabEventState?.data?.generatedAddress, tabEventState?.data?.generatedPrompt].every(Boolean);
  const reorderFiles = (newOrder: ImagePreview[]) => {
    tabEventState.fireEvent({ photos: [...newOrder] });
  };
  const deleteFile = (id: number) => {
    const photos = tabEventState?.data?.photos ? tabEventState.data.photos.filter(preview => preview.lastModified !== id) : [];
    tabEventState.fireEvent({ photos: photos });
  };

  const matches: tMatch[] = [
    {
      searchFn: searchByPartOfClass(['ai-prompt-input']),
      transformChild: child => (
        <Input
          template={child}
          value={tabEventState?.data?.prompt ? tabEventState.data.prompt : ''}
          inputProps={{ placeholder: child.props.placeholder }}
          onChange={e => {
            tabEventState.fireEvent({ prompt: e.currentTarget.value });
          }}
        />
      ),
    },
    {
      searchFn: searchByPartOfClass(['address-input']),
      transformChild: child => (
        <SearchAddressCombobox
          className={child.props.className}
          placeholder={child.props.placeholder}
          name='address'
          id='address-input'
          onPlaceSelected={place => tabEventState.fireEvent({ generatedAddress: place })}
        />
      ),
    },
    {
      searchFn: searchByPartOfClass(['card-upload-wrapper']),
      transformChild: child => (
        <RxDropzone
          className={'card-upload-wrapper'}
          onFileUpload={(newFiles: ImagePreview[]) => {
            const photos = tabEventState?.data?.photos ? tabEventState.data.photos : [];
            tabEventState.fireEvent({ photos: [...photos, ...newFiles] });
          }}
          inputId='agent_image'
        >
          {child.props.children}
        </RxDropzone>
      ),
    },
    {
      searchFn: searchByPartOfClass(['image-bank']),
      transformChild: child => {
        const photos = tabEventState?.data?.photos ? tabEventState.data.photos : [];
        return photos?.length > 0 ? <RxDragNDrop files={photos} template={child} reorderFiles={reorderFiles} deleteFile={deleteFile} /> : <></>;
      },
    },
    {
      searchFn: searchByPartOfClass(['f-button-neutral']),
      transformChild: child =>
        createElement(
          'button',
          { className: `${child.props.className} ${'disabled:bg-gray-500 disabled:cursor-not-allowed'}`, disabled: blockNext(), onClick: nextStepClick },
          [child.props.children],
        ),
    },
  ];
  return <>{transformMatchingElements(template, matches)}</>;
}
