import axios from 'axios';

export async function getAutoGeneratedPropertyInfo(description: string) {
  const response = await axios.post(
    `/api/prompt`,
    {
      description,
    },
    {
      headers: {
        'Content-Type': 'application/json',
      },
    },
  );
  return response.data;
}
